//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 5/8/2013 9:39:43 AM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface Antwoord : NSObject
{
}
@property double collarsize;
@property BOOL collarsizeSpecified;
@property double sleeve;
@property BOOL sleeveSpecified;
@property double shoulder;
@property BOOL shoulderSpecified;
@property double chest;
@property BOOL chestSpecified;
@property double belly;
@property BOOL bellySpecified;
@property double waist;
@property BOOL waistSpecified;
@property double arm;
@property BOOL armSpecified;
@property double wrist;
@property BOOL wristSpecified;
@property double back;
@property BOOL backSpecified;
@property double sizePredicition;
@property BOOL sizePredicitionSpecified;
@property (nonatomic, copy) NSString *bmi;
@property (nonatomic, copy) NSString *underBust;
@property (nonatomic, copy) NSString *upperBust;
@property (nonatomic, copy) NSString *hips;
@property (nonatomic, copy) NSString *gender;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
